name: 'Setup R & Bioconductor'
inputs:
  bioc-version:
    description: 'Version of Bioconductor'
    required: true
    default: 'devel'
  bioc-mirror:
    description: ''
    required: false
    default: 'https://www.bioconductor.org'
  use-public-rspm:
    description: 'Should the public Rstudio Package Manager be used to install packages.'
    required: false
    default: true
  Ncpus:
    description: 'Set the R option `Ncpus` to this value.'
    required: false
    default: 3
runs:
  using: "composite"
  steps:
  # - id: find-versions
  #   run: |
  #     RVERSION=$(Rscript "${{ github.action_path }}/get-r-version.R" "${{ github.action_path }}/bioc-version-map.csv" ${{ inputs.bioc-version }} r_version)
  #     RTOOLS=$(Rscript "${{ github.action_path }}/get-r-version.R" "${{ github.action_path }}/bioc-version-map.csv" ${{ inputs.bioc-version }} rtools)
  #     BIOCVERSION=$(Rscript "${{ github.action_path }}/get-r-version.R" "${{ github.action_path }}/bioc-version-map.csv" ${{ inputs.bioc-version }} bioc_version_explicit)
  #     echo "r-version=$(echo ${RVERSION})" >> $GITHUB_OUTPUT
  #     echo "rtools-version=$(echo ${RTOOLS})" >> $GITHUB_OUTPUT
  #     echo "bioc-version=$(echo ${BIOCVERSION})" >> $GITHUB_OUTPUT
  #     echo "R_BIOC_VERSION=${BIOCVERSION}" >> $GITHUB_ENV
  #   shell: bash
  
  - id: find-versions
    run: |
      RVERSION=$(sh "${GITHUB_ACTION_PATH}/get-r-version.sh" "${GITHUB_ACTION_PATH}/bioc-version-map.csv" ${{ inputs.bioc-version }} r_version)
      RTOOLS=$(sh "${GITHUB_ACTION_PATH}/get-r-version.sh" "$${GITHUB_ACTION_PATH}/bioc-version-map.csv" ${{ inputs.bioc-version }} rtools)
      BIOCVERSION=$(sh "${GITHUB_ACTION_PATH}/get-r-version.sh" "${GITHUB_ACTION_PATH}/bioc-version-map.csv" ${{ inputs.bioc-version }} bioc_version_explicit)
      echo "r-version=$(echo ${RVERSION})" >> $GITHUB_OUTPUT
      echo "rtools-version=$(echo ${RTOOLS})" >> $GITHUB_OUTPUT
      echo "bioc-version=$(echo ${BIOCVERSION})" >> $GITHUB_OUTPUT
      echo "R_BIOC_VERSION=${BIOCVERSION}" >> $GITHUB_ENV
    shell: bash

  - uses: r-lib/actions/setup-r@v2
    with:
      r-version: ${{ steps.find-versions.outputs.r-version }}
      Ncpus: ${{ inputs.Ncpus }}
      use-public-rspm: ${{ inputs.use-public-rspm }}
      rtools-version: ${{ steps.find-versions.outputs.rtools-version }}

  - name: Download Renviron
    run: |
      download.file('https://bioconductor.org/checkResults/${{ inputs.bioc-version }}/bioc-LATEST/Renviron.bioc', destfile = '~/.Renviron', mode = 'wb')
    shell: Rscript {0}

  - name: Setting Bioconductor mirror
    run: |
      write('options(BioC_mirror = "${{ inputs.bioc-mirror }}")', file = '~/.Rprofile', append = TRUE)
    shell: Rscript {0}

  - name: Install and initialize BiocManager
    run: |
      install.packages(c("BiocManager", "remotes"), quiet = TRUE)
      BiocManager::install(version = "${{ steps.find-versions.outputs.bioc-version }}", ask = FALSE)
    shell: Rscript {0}
